Repository gardener/falco-event-ingestor, pull requests merged in 2024-09, with the labels that each got.

#22 Deploy updates
  chart/templates/_helpers.yaml
  chart/templates/ingestor-deployment.yaml
  chart/templates/ingestor-ingress.yaml
  chart/templates/ingestor-secret.yaml
  chart/templates/ingestor-service.yaml
  chart/templates/intestor-vpa.yaml
  chart/values.yaml
  pkg/postgres/postgres.go
Labels: needs/ok-to-test, needs/review, size/s

#23 Rename ingestor tls secret
  chart/templates/ingestor-ingress.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#25 Raise rate limits for testing
  chart/values.yaml
  pkg/server/server.go
Labels: reviewed/lgtm, needs/ok-to-test, needs/review, size/xs

#26 correct directory structure, add ingestor annotation
  charts/falco-event-ingestor/Chart.yaml
  charts/falco-event-ingestor/templates/_helpers.yaml
  charts/falco-event-ingestor/templates/ingestor-certificate.yaml
  charts/falco-event-ingestor/templates/ingestor-configmap.yaml
  charts/falco-event-ingestor/templates/ingestor-deployment.yaml
  charts/falco-event-ingestor/templates/ingestor-ingress.yaml
  charts/falco-event-ingestor/templates/ingestor-secret.yaml
  charts/falco-event-ingestor/templates/ingestor-service.yaml
  charts/falco-event-ingestor/templates/intestor-vpa.yaml
  charts/falco-event-ingestor/values.yaml
Labels: needs/ok-to-test, needs/rebase, needs/review, size/xs

#27 Allow external traffic to ingestor
  charts/falco-event-ingestor/templates/ingestor-service.yaml
Labels: needs/review

#28 fix typo
  charts/falco-event-ingestor/templates/ingestor-service.yaml
Labels: needs/ok-to-test, needs/review, size/xs
